"use client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { DatePicker } from "~/components/datepicker";
import Spinner from "~/components/ui/spinner";

const Home: NextPage = () => {
  const [date, setDate] = useState<Date | undefined>();

  return (
    <>
      <Head>
        <title>Restaurant App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center h-screen gap-4 align-middle">
        <div>
          You have selected: {date?.toUTCString()}
        </div>
        <DatePicker date={date} setDate={setDate} />
        {date && true ? (
          // <Menu />
          null
        ) : (
          <div>
            <Spinner />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
