import { type NextPage } from "next";
import Head from "next/head";
import { DatePicker } from "~/components/datepicker";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DatePicker />
      </main>
    </>
  );
};

export default Home;
